# Generated by Django 3.2.18 on 2023-05-14 15:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('student_management_app', '0003_alter_customuser_first_name'),
    ]

    operations = [
        migrations.DeleteModel(
            name='LeaveReportStudent',
        ),
    ]
